version: '3.7'

services:
  postgres:
    container_name: postgres_tabnews
    image: postgres:alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      TZ: GMT
    ports:
      - 5432:5432
